# Generated by Django 4.1.6 on 2023-02-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='default')),
                ('day', models.IntegerField(default=1)),
                ('uuid', models.TextField(default='', unique=True)),
            ],
            options={
                'db_table': 'Image',
            },
        ),
    ]
