# Generated by Django 4.1.6 on 2023-02-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.TextField(default='default'),
        ),
    ]
