# Generated by Django 4.1.6 on 2023-02-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0002_image_uuid_name_alter_image_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='Image',
        ),
    ]
