# Generated by Django 4.1.6 on 2023-02-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.TextField()),
                ('kor', models.TextField()),
                ('day', models.IntegerField()),
                ('isDone', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Word',
            },
        ),
    ]
