# Generated by Django 4.1.6 on 2023-02-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Word', '0002_delete_fuck'),
    ]

    operations = [
        migrations.CreateModel(
            name='FUCK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField()),
            ],
        ),
    ]
