# Generated by Django 4.1.6 on 2023-02-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Word', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FUCK',
        ),
    ]
